### PR TITLE
Adapt linter

### PR DESCRIPTION
**Pull request by HafnerMichael**
## Description

Use flake8 as linter to also check the naming conventions

### CODE REVIEW

**Comment by m-langer** [comment]
Can this linter do everything or should we just leave both of them in there?

**Comment by HafnerMichael** [comment]
> Can this linter do everything or should we just leave both of them in there?

There is no need because flake uses pycodestyle internally [here](https://github.com/PyCQA/pep8-naming)

**Comment by m-langer** [comment]
Alright. Then the only fix I can see is the problem of the linter.

**Comment by Xetiic** [comment]
Since the abstract classifier is blocking this pr anyway, add this here, or postpone this pr and rebase it once the abstract classifier is fixed?

**Comment by HafnerMichael** [comment]
I would suggest to merge it, we just introduce a new functionality and from now on the repo follows those coding conventions.
If you want to stick on the gh worklfow we can create a issue and resolve it in combination with #9

**Review by Xetiic — APPROVED** [review]

**Review by m-langer — APPROVED** [review]
I updated the step name in the workflow file to represent the current linter

**Pull request merged**
